// ---------------------------------------------------------------------------
// Holiday 2026 — trip data
// Edit STAYS to correct dates/locations. Edit OPTIONS to add/remove activities.
// Everything else in the app is driven off this file.
// ---------------------------------------------------------------------------

const TRIP = {
  name: "Holiday 2026",
  travelers: "Bram & partner (+ little one, 2y)",
  start: "2026-08-24",
  end: "2026-09-11",
};

// Each stay = one accommodation block. `confirmed` marks whether it's a real
// booking (from your inbox) or a placeholder you still need to fill in.
const STAYS = [
  {
    id: "ehrwald",
    name: "Romantik Hotel Spielmann",
    place: "Ehrwald, Tyrol, Austria",
    region: "tyrol",
    address: "Wettersteinstraße 24, 6632 Ehrwald, Austria",
    checkIn: "2026-08-24",
    checkOut: "2026-08-27",
    confirmed: true,
    notes: "Suite Family South, half-board. Booking DSRAF5H00MGGV.",
  },
  {
    id: "heiligenblut",
    name: "Hieserhof – Superior Alpine Apartments",
    place: "Heiligenblut, Carinthia, Austria",
    region: "carinthia",
    address: "Hof 15, 9844 Heiligenblut, Austria",
    checkIn: "2026-08-27",
    checkOut: "2026-09-02",
    confirmed: true,
    notes: "Host Hermann Tribuser, +43 699 18104804. Kitchen fully equipped.",
  },
  {
    id: "istria",
    name: "Villa-Osmium",
    place: "Smoljanci, Svetvinčenat, Istria, Croatia",
    region: "istria",
    address: "73 Smoljanci, 52342 Smoljanci (Svetvinčenat), Croatia",
    checkIn: "2026-09-02",
    checkOut: "2026-09-09",
    confirmed: true,
    notes: "Booking 6048311160. Baby bed & high chair arranged with host.",
  },
  {
    id: "drivehome",
    name: "Drive home (not booked yet)",
    place: "Route back to Vught, Netherlands",
    region: "travel",
    address: "",
    checkIn: "2026-09-09",
    checkOut: "2026-09-11",
    confirmed: false,
    notes:
      "No hotel booked yet. ~1,300km / 13-14h driving total. Suggested 1-stop split below — add your own stop in Settings once booked.",
  },
];

// Suggested (unbooked) overnight stop for the drive home — editable/removable
// in the app. Roughly midpoint, on-route via Slovenia/Austria/Germany.
const SUGGESTED_STOPOVERS = [
  {
    name: "Salzburg area, Austria",
    why: "~750km from Istria, ~600km left to Vught the next day. Easy motorway access, plenty of family-friendly overnight stops.",
  },
  {
    name: "Nuremberg area, Germany",
    why: "Slightly further (~850km from Istria) but splits day 2 shorter (~500km), and breaks up the drive with a historic old town if you want to stretch legs.",
  },
];

// ---------------------------------------------------------------------------
// Curated options per region. Each option is scored against the day's
// question-flow answers to produce the "top choices" for that day.
//
// tags:
//   category:     nature | water | culture | food | adventure | chill
//   activityType: hiking | biking | swimming | relaxing (optional — only set
//                 when the option is clearly one of these; used for its own
//                 filter/badge, separate from category)
//   effort:       low | medium | high
//   weather:      sunny | any | indoor  (best-suited conditions)
//   kidFit:       easy    — toddler can walk/bike it themselves, short & flat
//                 carrier — fine with a toddler in a hiking carrier/child seat,
//                           not fine for a toddler to self-mobilize
//                 none    — adults only (technical, too long, or genuinely
//                           unsafe with a small child along)
//   distanceLabel: optional human-readable distance/route length
//   duration:     approx hours
// ---------------------------------------------------------------------------

const OPTIONS = {
  tyrol: [
    {
      id: "ty-ehrwalder-alm",
      title: "Ehrwalder Alm gondola + alpine meadow",
      desc: "Easy gondola ride to 1,500m, flat meadow trails, playground, trampolines and go-karts right at the top station. Ehrwalder Alm inn for Tirolean lunch with a view.",
      mapsQuery: "Ehrwalder Almbahn, Ehrwald, Austria",
      category: "nature",
      effort: "low",
      weather: "sunny",
      kidFit: "easy",
      duration: 3,
    },
    {
      id: "ty-wassererlebnisweg",
      title: "Wassererlebnisweg Zugspitzi (water trail)",
      desc: "Flat, free, stroller-friendly water-play trail starting right at the Ehrwalder Alm cable car station — streams, pumps and splash spots kids love.",
      mapsQuery: "Wassererlebnisweg Zugspitzi, Ehrwalder Alm, Ehrwald, Austria",
      category: "water",
      effort: "low",
      weather: "sunny",
      kidFit: "easy",
      duration: 1.5,
    },
    {
      id: "ty-blindsee",
      title: "Blindsee mountain lake",
      desc: "Turquoise forest lake reachable via a short forest-road walk (€4 entry). Swimming, a pebble beach, and a scenic loop for an evening stroll — a proper lounge-all-afternoon spot.",
      mapsQuery: "Blindsee, Biberwier, Austria",
      category: "water",
      activityType: "relaxing",
      effort: "low",
      weather: "sunny",
      kidFit: "easy",
      duration: 2.5,
    },
    {
      id: "ty-heiterwangersee",
      title: "Heiterwanger See boat & paddle day",
      desc: "Bigger recreational lake: rowboat/paddleboard rental, hop-on-hop-off boat tours, shaded lakeside paths — easy to keep a toddler entertained lakeside.",
      mapsQuery: "Heiterwanger See, Heiterwang, Austria",
      category: "water",
      effort: "low",
      weather: "sunny",
      kidFit: "easy",
      duration: 3,
    },
    {
      id: "ty-zugspitze",
      title: "Zugspitzbahn to the summit (2,962m)",
      desc: "10-minute cable car to Germany's/Austria's highest point — glass floor platform, snow chamber, 4-country panorama. Big-weather-window activity, less toddler nap-friendly.",
      mapsQuery: "Tiroler Zugspitzbahn Talstation, Ehrwald, Austria",
      category: "adventure",
      effort: "medium",
      weather: "sunny",
      kidFit: "carrier",
      duration: 4,
    },
    {
      id: "ty-seebensee",
      title: "Seebensee lake hike",
      desc: "5.5km round trip (~90 min each way) through meadow and forest to a striking alpine lake below the Drachenkopf cliffs. Doable with a hiking carrier, not a stroller.",
      mapsQuery: "Seebensee, Ehrwald, Austria",
      category: "nature",
      activityType: "hiking",
      distanceLabel: "5.5 km round trip",
      effort: "high",
      weather: "sunny",
      kidFit: "carrier",
      duration: 4,
    },
    {
      id: "ty-bichlbach-park",
      title: "Bichlbach Adventure Park",
      desc: "Rope courses, zip-lining and a 90m Flying Fox for grown-ups, plus mini-golf, kids' rafting and a natural swimming lake for the little one.",
      mapsQuery: "Erlebnispark Bichlbach, Bichlbach, Austria",
      category: "adventure",
      effort: "medium",
      weather: "sunny",
      kidFit: "easy",
      duration: 4,
    },
    {
      id: "ty-gamsalm",
      title: "Gamsalm mountain hut lunch",
      desc: "Sunny terrace hut with proper local food (don't skip the Kaiserschmarrn) and a kids' playground on site — a relaxed half-day if the weather's mixed.",
      mapsQuery: "Gamsalm, Ehrwald, Austria",
      category: "food",
      activityType: "relaxing",
      effort: "low",
      weather: "any",
      kidFit: "easy",
      duration: 2,
    },
    {
      id: "ty-tillfussalm-walk",
      title: "Walk to Tillfussalm, Gaital valley",
      desc: "Easy valley walk from Ehrwald or Leutasch to a traditional Alm — stroller-accessible the whole way, real Tirolean hut food at the end. A gentler altitude combo than Gamsalm's more built-up surroundings.",
      mapsQuery: "Tillfussalm, Ehrwald, Austria",
      category: "nature",
      activityType: "hiking",
      distanceLabel: "flat valley walk, stroller-friendly",
      effort: "low",
      weather: "any",
      kidFit: "easy",
      duration: 3,
    },
    {
      id: "ty-e-bike-seebenalm",
      title: "E-bike to Seebenalm",
      desc: "Gentle ~9km forest ride from the Ehrwalder Almbahn valley station up to Seebenalm (~150m ascent) — rent at Radlgaudi in the village centre, one of the easiest family e-bike routes in the valley.",
      mapsQuery: "Radlgaudi, Ehrwald, Austria",
      category: "adventure",
      activityType: "biking",
      distanceLabel: "~9 km, ~150 m ascent",
      effort: "medium",
      weather: "sunny",
      kidFit: "carrier",
      duration: 3,
    },
    {
      id: "ty-mooswirt-dinner",
      title: "Dinner at Bettina's Mooswirt",
      desc: "Authentic Tirolean farmhouse kitchen just outside the village, outdoor patio warmed by an open wood fire — a proper sit-down dinner after a big day.",
      mapsQuery: "Bettina's Mooswirt, Ehrwald, Austria",
      category: "food",
      activityType: "relaxing",
      effort: "low",
      weather: "any",
      kidFit: "easy",
      duration: 2,
    },
    {
      id: "ty-rainy-museum",
      title: "Zugspitze summit museum + snow world (indoor)",
      desc: "If it's socked in below, go up anyway — the summit museums and snow chamber are indoors and still spectacular above the clouds.",
      mapsQuery: "Zugspitze summit station, Austria",
      category: "culture",
      effort: "low",
      weather: "indoor",
      kidFit: "easy",
      duration: 3,
    },
    {
      id: "ty-grubigstein-hike",
      title: "Grubigstein summit hike (2,233m)",
      desc: "Real alpine hike from Lermoos: steep, sure-footedness required, loose scree near the top — genuinely challenging, not a stroll. Cable car down from the Grubighütte if you want to shortcut the descent. Adults only.",
      mapsQuery: "Grubigstein, Lermoos, Austria",
      category: "nature",
      activityType: "hiking",
      distanceLabel: "~6.3 km round trip, ~1,180 m ascent, ~3.5-4h",
      effort: "high",
      weather: "sunny",
      kidFit: "none",
      duration: 4,
    },
  ],

  carinthia: [
    {
      id: "ca-kaiser-franz-josef",
      title: "Kaiser-Franz-Josefs-Höhe + Pasterze Glacier viewpoint",
      desc: "The classic Grossglockner High Alpine Road stop: wide accessible terraces looking straight at Austria's highest peak and the Pasterze Glacier. Marmot-spotting for the kids, restaurant on site.",
      mapsQuery: "Kaiser-Franz-Josefs-Höhe, Heiligenblut, Austria",
      category: "nature",
      activityType: "relaxing",
      effort: "low",
      weather: "sunny",
      kidFit: "easy",
      duration: 3,
    },
    {
      id: "ca-glocknerhaus-walk",
      title: "Glocknerhaus + Gamsgrubenweg walk",
      desc: "Traditional mountain-house food (Käsespätzle, Kaiserschmarrn) right at Kaiser-Franz-Josefs-Höhe, at 2,369m, easily reached by car. Combine with the short, flat Gamsgrubenweg — tunnels along the cliff face to a glacier viewpoint (currently maintained as far as Tunnel 6, check current status locally).",
      mapsQuery: "Glocknerhaus, Heiligenblut, Austria",
      category: "nature",
      activityType: "hiking",
      distanceLabel: "short, flat, mostly through tunnels",
      effort: "low",
      weather: "sunny",
      kidFit: "carrier",
      duration: 3,
    },
    {
      id: "ca-grossglockner-drive",
      title: "Grossglockner High Alpine Road, full drive",
      desc: "Toll scenic road with a stop every 30-60 min — Edelweissspitze (highest point reachable by car, hairpin access road), Hochtor Pass, and endless viewpoints. Easy to keep short with frequent breaks.",
      mapsQuery: "Grossglockner Hochalpenstraße, Austria",
      category: "nature",
      effort: "low",
      weather: "sunny",
      kidFit: "easy",
      duration: 5,
    },
    {
      id: "ca-gossnitz-waterfall",
      title: "Gössnitz waterfall walk",
      desc: "Short, mostly flat walk from Heiligenblut village to a proper alpine waterfall — one of the easiest real hikes in the valley, good with a stroller partway.",
      mapsQuery: "Gössnitzfall, Heiligenblut, Austria",
      category: "nature",
      activityType: "hiking",
      distanceLabel: "~2.6 km round trip",
      effort: "low",
      weather: "any",
      kidFit: "easy",
      duration: 2,
    },
    {
      id: "ca-heiligenblut-village",
      title: "Heiligenblut village + pilgrimage church",
      desc: "Postcard alpine village under the Grossglockner, gothic pilgrimage church, small cafés — an easy low-key wander for a slow morning.",
      mapsQuery: "Pfarrkirche Heiligenblut, Austria",
      category: "culture",
      activityType: "relaxing",
      effort: "low",
      weather: "any",
      kidFit: "easy",
      duration: 1.5,
    },
    {
      id: "ca-glacier-railway",
      title: "Grossglockner Glacier Railway / panoramic cable car",
      desc: "Ride up for glacier and summit views without a long hike — a good option when little legs (or patience) are the limiting factor.",
      mapsQuery: "Gletscherbahn Kaiser-Franz-Josefs-Höhe, Austria",
      category: "adventure",
      effort: "low",
      weather: "sunny",
      kidFit: "easy",
      duration: 2.5,
    },
    {
      id: "ca-hohe-tauern-hike",
      title: "Hohe Tauern National Park day hike",
      desc: "Proper trail into the national park among the 3,000m peaks — best with a carrier rather than a stroller, big scenery pay-off.",
      mapsQuery: "Hohe Tauern National Park, Austria",
      category: "nature",
      activityType: "hiking",
      distanceLabel: "~6 km",
      effort: "high",
      weather: "sunny",
      kidFit: "carrier",
      duration: 5,
    },
    {
      id: "ca-indoor-pool",
      title: "Indoor pool & sauna afternoon",
      desc: "Heiligenblut has an indoor swimming pool — the easy fallback for a rainy or low-energy day with a toddler.",
      mapsQuery: "Hallenbad Heiligenblut, Austria",
      category: "chill",
      activityType: "swimming",
      effort: "low",
      weather: "indoor",
      kidFit: "easy",
      duration: 2,
    },
    {
      id: "ca-e-bike",
      title: "Valley e-bike ride",
      desc: "Gentle e-bike route along the valley floor — flatter than it looks from the road, doable as a family if you've got a child seat/trailer.",
      mapsQuery: "e-bike rental Heiligenblut, Austria",
      category: "adventure",
      activityType: "biking",
      distanceLabel: "Glockner Radweg valley path — go as far as you like (up to 80 km one-way)",
      effort: "medium",
      weather: "sunny",
      kidFit: "carrier",
      duration: 3,
    },
    {
      id: "ca-sonnblick-dinner",
      title: "Dinner at Landgasthof Sonnblick",
      desc: "Carinthian cheese noodles (Kasnudeln), Glockner lamb, and Reindling for dessert — a proper regional dinner right in the village, good local wine list too.",
      mapsQuery: "Landgasthof Sonnblick, Heiligenblut, Austria",
      category: "food",
      activityType: "relaxing",
      effort: "low",
      weather: "any",
      kidFit: "easy",
      duration: 2,
    },
    {
      id: "ca-millstatter-see",
      title: "Millstätter See lake day",
      desc: "The nicest proper lake within reach — family-friendly swimming beaches, warm water for an alpine lake, boat rental if you want it. It's a real trip (~1h15 from Heiligenblut via the Mölltal valley), so treat it as a full day out, not a quick dip.",
      mapsQuery: "Millstätter See, Austria",
      category: "water",
      activityType: "relaxing",
      effort: "low",
      weather: "sunny",
      kidFit: "easy",
      duration: 5,
    },
    {
      id: "ca-mohar-hike",
      title: "Mohar summit hike (2,604m)",
      desc: "Real summit hike from the Glocknerblick mountain inn — non-glacier, no technical climbing, but sustained steep ascent and genuine alpine terrain. Sweeping views to the Grossglockner and Sonnblick. Adults only.",
      mapsQuery: "Glocknerblick, Heiligenblut, Austria",
      category: "nature",
      activityType: "hiking",
      distanceLabel: "~560 m ascent, ~4-5h round trip",
      effort: "high",
      weather: "sunny",
      kidFit: "none",
      duration: 5,
    },
  ],

  istria: [
    {
      id: "is-bale-beach",
      title: "Bale / Vodnjan coast beach day",
      desc: "Closest coastline to Smoljanci (~15-20 min drive) — mixed rock/pebble bays with shallow entry points, good for a toddler paddling with reef shoes.",
      mapsQuery: "Bale beach, Croatia",
      category: "water",
      activityType: "swimming",
      effort: "low",
      weather: "sunny",
      kidFit: "easy",
      duration: 4,
    },
    {
      id: "is-bale-forest-walk",
      title: "Chapel of St. John forest trail, Bale",
      desc: "Shaded loop through forest and dry-stone-wall countryside just outside Bale — the easiest real hike near the villa, olive groves and kažuni along the way.",
      mapsQuery: "Chapel of St. John, Bale, Croatia",
      category: "nature",
      activityType: "hiking",
      distanceLabel: "4.4 km loop",
      effort: "low",
      weather: "any",
      kidFit: "carrier",
      duration: 2,
    },
    {
      id: "is-vrsar-funtana-coastal",
      title: "Vrsar–Funtana coastal path",
      desc: "Flat, easy coastal walk linking two harbour towns, sea views the whole way — about as low-effort as a real hike gets. Good for an evening stroll before dinner.",
      mapsQuery: "Vrsar to Funtana coastal path, Croatia",
      category: "nature",
      activityType: "hiking",
      distanceLabel: "~3 km one-way, flat",
      effort: "low",
      weather: "any",
      kidFit: "easy",
      duration: 2,
    },
    {
      id: "is-kamenjak-coastal",
      title: "Cape Kamenjak coastal walk",
      desc: "Wild, undeveloped headland south of Premantura — rocky coves, cliffside path, and a dinosaur-footprint trail near the entrance that's a reliable toddler hit. Walk as little or as much of the ~11.6km loop as you like.",
      mapsQuery: "Cape Kamenjak, Premantura, Croatia",
      category: "nature",
      activityType: "hiking",
      distanceLabel: "up to ~11.6 km loop — go as far as you like",
      effort: "medium",
      weather: "sunny",
      kidFit: "carrier",
      duration: 3,
    },
    {
      id: "is-ucka-vojak-hike",
      title: "Vojak summit hike, Učka Nature Park",
      desc: "Istria's highest point (1,401m): well-marked forest trail from the Poklon pass to a stone lookout tower with views across the whole peninsula to the Kvarner Bay. Real elevation gain, steady rather than technical. About 1h15 drive from Smoljanci.",
      mapsQuery: "Poklon, Učka Nature Park, Croatia",
      category: "nature",
      activityType: "hiking",
      distanceLabel: "~7 km round trip, ~470 m ascent, ~3-3.5h",
      effort: "high",
      weather: "sunny",
      kidFit: "carrier",
      duration: 4,
    },
    {
      id: "is-rovinj",
      title: "Rovinj old town wander",
      desc: "Istria's postcard town — pastel houses, hilltop church, harbour-front gelato. Cobbled and hilly, fine with a carrier or light stroller.",
      mapsQuery: "Rovinj old town, Croatia",
      category: "culture",
      activityType: "relaxing",
      effort: "low",
      weather: "any",
      kidFit: "carrier",
      duration: 3,
    },
    {
      id: "is-pula-walk",
      title: "Pula old town Roman walk",
      desc: "Start at the Arena (the only Roman amphitheatre with all four side towers intact), then wander to the Forum, the Temple of Augustus, and the Arch of the Sergii along the waterfront — all walkable in one easy loop.",
      mapsQuery: "Pula Arena, Croatia",
      category: "culture",
      activityType: "relaxing",
      effort: "low",
      weather: "any",
      kidFit: "carrier",
      duration: 3,
    },
    {
      id: "is-porec-walk",
      title: "Poreč old town + Euphrasian Basilica",
      desc: "Compact peninsula old town built for wandering — the 6th-century Euphrasian Basilica (UNESCO, stunning Byzantine mosaics) is a couple of minutes from the Decumanus and the waterfront promenade either way.",
      mapsQuery: "Euphrasian Basilica, Poreč, Croatia",
      category: "culture",
      activityType: "relaxing",
      effort: "low",
      weather: "any",
      kidFit: "carrier",
      duration: 2.5,
    },
    {
      id: "is-rijeka-korzo",
      title: "Rijeka: Korzo & waterfront",
      desc: "A proper city change of pace from the villages — the Korzo pedestrian street, the riverside, and a lively old town. Furthest of the town options (~1h15 drive), worth it as a full outing rather than a quick stop.",
      mapsQuery: "Korzo, Rijeka, Croatia",
      category: "culture",
      activityType: "relaxing",
      effort: "low",
      weather: "any",
      kidFit: "carrier",
      duration: 4,
    },
    {
      id: "is-dino-park",
      title: "Dino Park Funtana",
      desc: "80+ life-size dinosaurs in a forest park, mini funfair, playgrounds — reliably a toddler favourite and shaded for hot days.",
      mapsQuery: "Dinopark Funtana, Croatia",
      category: "adventure",
      effort: "low",
      weather: "sunny",
      kidFit: "easy",
      duration: 3,
    },
    {
      id: "is-aquapark",
      title: "Aquapark Istralandia",
      desc: "Water park with a dedicated splash/family zone as well as bigger slides — good full-day option, note some slides have 1m/1.2m height minimums.",
      mapsQuery: "Istralandia Aquapark, Novigrad, Croatia",
      category: "water",
      activityType: "swimming",
      effort: "medium",
      weather: "sunny",
      kidFit: "easy",
      duration: 5,
    },
    {
      id: "is-bale-e-bike",
      title: "E-bike from Bale towards the coast",
      desc: "Rent at SBC Bale (inside Camping Mon Perin) and ride quiet roads through olive groves toward the San Polo/Colone beaches or Rovinj — flat, easy family riding.",
      mapsQuery: "SBC Bale bike rental, Bale, Croatia",
      category: "adventure",
      activityType: "biking",
      distanceLabel: "flexible — flat coastal roads, go as far as you like",
      effort: "medium",
      weather: "sunny",
      kidFit: "carrier",
      duration: 3,
    },
    {
      id: "is-sanc-michael",
      title: "Sanc. Michael medieval park",
      desc: "Medieval-themed park with archery, a carousel, farm-animal interactions and traditional food — built for families with young kids.",
      mapsQuery: "Medieval Theme Park Sanc. Michael, Svetvinčenat, Croatia",
      category: "adventure",
      effort: "low",
      weather: "sunny",
      kidFit: "easy",
      duration: 3,
    },
    {
      id: "is-drijade-farm",
      title: "Drijade Farm visit",
      desc: "Small interactive farm with 100+ animals near Svetvinčenat, low-key and close to the villa — an easy morning if you don't want to drive far.",
      mapsQuery: "Farma Drijade, Svetvinčenat, Croatia",
      category: "nature",
      effort: "low",
      weather: "any",
      kidFit: "easy",
      duration: 2,
    },
    {
      id: "is-morosini-castle",
      title: "Svetvinčenat's own Morosini-Grimani Castle",
      desc: "Right in the village you're staying near — courtyard, escape-room option for the grown-ups if you can get a sitter for an hour.",
      mapsQuery: "Morosini-Grimani Castle, Svetvinčenat, Croatia",
      category: "culture",
      effort: "low",
      weather: "any",
      kidFit: "easy",
      duration: 1.5,
    },
    {
      id: "is-pazin-cave",
      title: "Pazin Cave + zip-lining",
      desc: "Dramatic karst chasm below Pazin castle; zip-lines for the adults while younger ones watch from the viewpoint.",
      mapsQuery: "Pazinska jama (Pazin Cave), Croatia",
      category: "adventure",
      effort: "medium",
      weather: "any",
      kidFit: "carrier",
      duration: 3,
    },
    {
      id: "is-konoba-dinner",
      title: "Dinner at Konoba Klarići",
      desc: "Homemade Istrian cooking right in the village — stews, hand-rolled pasta with truffles, meat and veg from their own farm. Cosy, unpretentious, walkable from the villa.",
      mapsQuery: "Konoba Klarići, Svetvinčenat, Croatia",
      category: "food",
      activityType: "relaxing",
      effort: "low",
      weather: "any",
      kidFit: "easy",
      duration: 2,
    },
    {
      id: "is-konoba-jure-rovinj",
      title: "Dinner at Konoba Jure, Rovinj",
      desc: "Genuinely local, not a tourist-strip place — a 20-minute walk from the old town, family-run, no fixed menu (just what they gathered that day), served family-style in the middle of the table. Popular with locals; book ahead.",
      mapsQuery: "Konoba Jure, Rovinj, Croatia",
      category: "food",
      activityType: "relaxing",
      effort: "low",
      weather: "any",
      kidFit: "easy",
      duration: 2,
    },
    {
      id: "is-vodnjanka-pula",
      title: "Lunch at Trattoria Vodnjanka, Pula",
      desc: "Over 60 years running, a short walk from Pula's market and the ingredients it sources from — well away from the Arena tourist circuit despite being close by. The kind of place locals actually eat.",
      mapsQuery: "Trattoria Vodnjanka, Pula, Croatia",
      category: "food",
      activityType: "relaxing",
      effort: "low",
      weather: "any",
      kidFit: "easy",
      duration: 2,
    },
    {
      id: "is-dor-beach-club",
      title: "D'or Beach Club, Funtana",
      desc: "A proper beach club rather than just a beach — loungers, cocktails, resident DJ, chic-but-relaxed. Daytime is family-friendly lounging by the water; it leans more adult/lively in the evening.",
      mapsQuery: "D'or Beach Club, Funtana, Croatia",
      category: "food",
      activityType: "relaxing",
      effort: "low",
      weather: "sunny",
      kidFit: "easy",
      duration: 3,
    },
    {
      id: "is-pula-aquarium",
      title: "Pula Aquarium + amphitheatre",
      desc: "Indoor aquarium in a historic fort, combine with a look at the Roman arena in town — good rainy-day or midday-heat option.",
      mapsQuery: "Aquarium Pula, Croatia",
      category: "culture",
      effort: "low",
      weather: "indoor",
      kidFit: "easy",
      duration: 3,
    },
    {
      id: "is-scuba-diving",
      title: "Scuba diving off Rovinj (wrecks & reefs)",
      desc: "Two-tank boat dive with Diving Center Morski Puž — the SS Baron Gautsch wreck (39m, sunk 1914) is the big local draw, plus reef dives in the Rovinj archipelago. Bring or verify certification/logbook; deeper wreck dives usually want a recent dive history. Adults only.",
      mapsQuery: "Diving Center Morski Puž, Rovinj, Croatia",
      category: "adventure",
      activityType: "swimming",
      effort: "high",
      weather: "sunny",
      kidFit: "none",
      duration: 5,
    },
  ],

  travel: [
    {
      id: "tr-salzburg",
      title: "Break the drive around Salzburg",
      desc: "~750km from Istria, leaves a manageable ~600km for day two into Vught.",
      mapsQuery: "Salzburg, Austria",
      category: "chill",
      effort: "low",
      weather: "any",
      kidFit: "easy",
      duration: 1,
    },
    {
      id: "tr-nuremberg",
      title: "Break the drive around Nuremberg",
      desc: "~850km from Istria, shorter ~500km second day, old town worth an evening walk if you arrive with energy left.",
      mapsQuery: "Nuremberg, Germany",
      category: "chill",
      effort: "low",
      weather: "any",
      kidFit: "easy",
      duration: 1,
    },
  ],
};

// Question flow shown for every non-travel day.
const QUESTIONS = [
  {
    id: "weather",
    text: "What's the weather doing today?",
    multi: false,
    choices: [
      { label: "☀️ Sunny / warm", value: "sunny" },
      { label: "⛅ Mixed", value: "any" },
      { label: "🌧️ Rainy / cool", value: "indoor" },
    ],
  },
  {
    id: "energy",
    text: "How much energy / time do you have today?",
    multi: false,
    choices: [
      { label: "😴 Keep it short & easy", value: "low" },
      { label: "🚶 A solid half-day", value: "medium" },
      { label: "🏔️ Go big, full day", value: "high" },
    ],
  },
  {
    id: "mood",
    text: "What are you in the mood for?",
    multi: false,
    choices: [
      { label: "🌲 Nature", value: "nature" },
      { label: "💧 Water", value: "water" },
      { label: "🏛️ Culture", value: "culture" },
      { label: "🍽️ Eating & drinking", value: "food" },
      { label: "⚡ Adventure", value: "adventure" },
    ],
  },
  {
    id: "activityType",
    text: "Any particular type of activity?",
    multi: false,
    choices: [
      { label: "🥾 Hiking", value: "hiking" },
      { label: "🚴 Biking", value: "biking" },
      { label: "🏊 Swimming", value: "swimming" },
      { label: "😌 Relaxing", value: "relaxing" },
      { label: "🤷 No preference", value: "none" },
    ],
  },
  {
    id: "kids",
    text: "Kids with you today?",
    multi: false,
    choices: [
      { label: "Yes", value: true },
      { label: "No — anything goes", value: false },
    ],
  },
  {
    id: "kidsMobility",
    text: "How are the little ones getting around?",
    multi: false,
    showIf: (answers) => answers.kids === true,
    choices: [
      { label: "🚶 Own two feet / bike", value: "walk" },
      { label: "🎒 Carrier backpack is fine", value: "carrier" },
    ],
  },
];
